if (typeof translations == "undefined") {
  translations = {};
}

translations.en_US = {
  // header
  Search: "Search",
  // Nav menu
  Add: "Add",
  "By URIs": "By URIs",
  "By Torrents": "By Torrents",
  "By Metalinks": "By Metalinks",
  Manage: "Manage",
  "Pause All": "Pause All",
  "Resume Paused": "Resume Paused",
  "Purge Completed": "Purge Completed",
  Settings: "Settings",
  "Connection Settings": "Connection Settings",
  "Global Settings": "Global Settings",
  "Server info": "Server info",
  "About and contribute": "About and contribute",
  "Toggle navigation": "Toggle navigation",
  // body
  // nav side bar
  Miscellaneous: "Miscellaneous",
  "Global Statistics": "Global Statistics",
  About: "About",
  Displaying: "Displaying",
  of: "of",
  downloads: "downloads",
  Language: "Language",
  // download filters
  "Download Filters": "Download Filters",
  Running: "Running",
  Active: "Active",
  Waiting: "Waiting",
  Complete: "Complete",
  Error: "Error",
  Paused: "Paused",
  Removed: "Removed",
  "Hide linked meta-data": "Hide linked meta-data",
  Toggle: "Toggle",
  "Reset filters": "Reset filters",
  // download status
  Verifing: "Verifing",
  "Verify Pending": "Verify Pending",
  // starred properties
  "Quick Access Settings": "Quick Access Settings",
  Save: "Save",
  "Save settings": "Save settings",
  "Currently no download in line to display, use the":
    "Currently no download in line to display, use the",
  "download button to start downloading files!": "download button to start downloading files!",
  Peers: "Peers",
  "More Info": "More Info",
  Remove: "Remove",
  "# of": "# of",
  Length: "Length",
  // modals
  "Add Downloads By URIs": "Add Downloads By URIs",
  "- You can add multiple downloads (files) at the same time by putting URIs for each file on a separate line.":
    "- You can add multiple downloads (files) at the same time by putting URIs for each file on a separate line.",
  "- You can also add multiple URIs (mirrors) for the *same* file. To do this, separate the URIs by a space.":
    "- You can also add multiple URIs (mirrors) for the *same* file. To do this, separate the URIs by a space.",
  "- A URI can be HTTP(S)/FTP/BitTorrent-Magnet.": "- A URI can be HTTP(S)/FTP/BitTorrent-Magnet.",
  "Download settings": "Download settings",
  "Advanced settings": "Advanced settings",
  Cancel: "Cancel",
  Start: "Start",
  Choose: "Choose",
  "Quick Access (shown on the main page)": "Quick Access (shown on the main page)",
  // add torrent modal
  "Add Downloads By Torrents": "Add Downloads By Torrents",
  "- Select the torrent from the local filesystem to start the download.":
    "- Select the torrent from the local filesystem to start the download.",
  "- You can select multiple torrents to start multiple downloads.":
    "- You can select multiple torrents to start multiple downloads.",
  "- To add a BitTorrent-Magnet URL, use the Add By URI option and add it there.":
    "- To add a BitTorrent-Magnet URL, use the Add By URI option and add it there.",
  "Select Torrents": "Select Torrents",
  "Select a Torrent": "Select a Torrent",
  // add metalink modal
  "Add Downloads By Metalinks": "Add Downloads By Metalinks",
  "Select Metalinks": "Select Metalinks",
  "- Select the Metalink from the local filesystem to start the download.":
    "- Select the Metalink from the local filesystem to start the download.",
  "- You can select multiple Metalinks to start multiple downloads.":
    "- You can select multiple Metalinks to start multiple downloads.",
  "Select a Metalink": "Select a Metalink",
  // select file modal
  "Choose files to start download for": "Choose files to start download for",
  "Select to download": "Select to download",
  // settings modal
  "Aria2 RPC host and port": "Aria2 RPC host and port",
  "Enter the host": "Enter the host",
  "Enter the IP or DNS name of the server on which the RPC for Aria2 is running (default: localhost)":
    "Enter the IP or DNS name of the server on which the RPC for Aria2 is running (default: localhost)",
  "Enter the port": "Enter the port",
  "Enter the port of the server on which the RPC for Aria2 is running (default: 6800)":
    "Enter the port of the server on which the RPC for Aria2 is running (default: 6800)",
  "Enter the RPC path": "Enter the RPC path",
  "Enter the path for the Aria2 RPC endpoint (default: /jsonrpc)":
    "Enter the path for the Aria2 RPC endpoint (default: /jsonrpc)",
  "SSL/TLS encryption": "SSL/TLS encryption",
  "Enable SSL/TLS encryption": "Enable SSL/TLS encryption",
  "Enter the secret token (optional)": "Enter the secret token (optional)",
  "Enter the Aria2 RPC secret token (leave empty if authentication is not enabled)":
    "Enter the Aria2 RPC secret token (leave empty if authentication is not enabled)",
  "Enter the username (optional)": "Enter the username (optional)",
  "Enter the Aria2 RPC username (empty if authentication not enabled)":
    "Enter the Aria2 RPC username (empty if authentication not enabled)",
  "Enter the password (optional)": "Enter the password (optional)",
  "Enter the Aria2 RPC password (empty if authentication not enabled)":
    "Enter the Aria2 RPC password (empty if authentication not enabled)",
  "Enter base URL (optional)": "Enter base URL (optional)",
  "Direct Download": "Direct Download",
  "If supplied, links will be created to enable direct download from the Aria2 server.":
    "If supplied, links will be created to enable direct download from the Aria2 server.",
  "(Requires appropriate webserver to be configured.)":
    "(Requires appropriate webserver to be configured.)",
  "Save Connection configuration": "Save Connection configuration",
  Filter: "Filter",
  // server info modal
  "Aria2 server info": "Aria2 server info",
  "Aria2 Version": "Aria2 Version",
  "Features Enabled": "Features Enabled",
  // about modal
  "To download the latest version of the project, add issues or to contribute back, head on to":
    "To download the latest version of the project, add issues or to contribute back, head on to",
  "Or you can open the latest version in the browser through":
    "Or you can open the latest version in the browser through",
  Close: "Close",
  // lables
  "Download status": "Download status",
  "Download Speed": "Download Speed",
  "Upload Speed": "Upload Speed",
  "Estimated time": "Estimated time",
  "Download Size": "Download Size",
  Downloaded: "Downloaded",
  Progress: "Progress",
  "Download Path": "Download Path",
  Uploaded: "Uploaded",
  "Download GID": "Download GID",
  "Number of Pieces": "Number of Pieces",
  "Piece Length": "Piece Length",
  "Shutdown Server": "Shutdown Server",

  "The last connection attempt was unsuccessful. Trying another configuration":
    "The last connection attempt was unsuccessful. Trying another configuration",
  "Oh Snap!": "Oh Snap!",
  "Could not connect to the aria2 RPC server. Will retry in 10 secs. You might want to check the connection settings by going to Settings > Connection Settings":
    "Could not connect to the aria2 RPC server. Will retry in 10 secs. You might want to check the connection settings by going to Settings > Connection Settings",
  "Authentication failed while connecting to Aria2 RPC server. Will retry in 10 secs. You might want to confirm your authentication details by going to Settings > Connection Settings":
    "Authentication failed while connecting to Aria2 RPC server. Will retry in 10 secs. You might want to confirm your authentication details by going to Settings > Connection Settings",
  "Successfully connected to Aria2 through its remote RPC …":
    "Successfully connected to Aria2 through its remote RPC …",
  "Successfully connected to Aria2 through remote RPC, however the connection is still insecure. For complete security try adding an authorization secret token while starting Aria2 (through the flag --rpc-secret)":
    "Successfully connected to Aria2 through remote RPC, however the connection is still insecure. For complete security try adding an authorization secret token while starting Aria2 (through the flag --rpc-secret)",
  "Trying to connect to aria2 using the new connection configuration":
    "Trying to connect to aria2 using the new connection configuration",
  "Remove {{name}} and associated meta-data?": "Remove {{name}} and associated meta-data?",

  //Settings descriptions
  "Settings.all-proxy.desc": "Use a proxy server for all protocols. To override a previously defined proxy, use \"\". You also can override this setting and specify a proxy server for a particular protocol using --http-proxy, --https-proxy and --ftp-proxy options. This affects all downloads. The format of PROXY is [http://][USER:PASSWORD@]HOST[:PORT]. See also ENVIRONMENT section. Note: If user and password are embedded in proxy URI and they are also specified by --{http,https,ftp,all}-proxy-{user,passwd} options, those specified later override prior options. For example, if you specified http-proxy-user=myname, http-proxy-passwd=mypass in aria2.conf and you specified --http-proxy=\"http://proxy\" on the command-line, then you'd get HTTP proxy http://proxy with user myname and password mypass. Another example: if you specified on the command-line --http-proxy=\"http://user:pass@proxy\" --http-proxy-user=\"myname\" --http-proxy-passwd=\"mypass\", then you'd get HTTP proxy http://proxy with user myname and password mypass.One more example: if you specified in command-line --http-proxy-user=\"myname\" --http-proxy-passwd=\"mypass\" --http-proxy=\"http://user:pass@proxy\", then you'd get HTTP proxy http://proxy with user user and password pass.",
  "Settings.all-proxy-passwd.desc": 'Set password for all-proxy option.',
  "Settings.all-proxy-user.desc": 'Set user for all-proxy option.',
  "Settings.allow-overwrite.desc": "Restart download from scratch if the corresponding control file doesn't exist. See also auto-file-renaming option. Default: false",
  "Settings.allow-piece-length-change.desc": 'If false is given, aria2 aborts download when a piece length is different from one in a control file. If true is given, you can proceed but some download progress will be lost. Default: false',
  "Settings.always-resume.desc": 'Always resume download. If true is given, aria2 always tries to resume download and if resume is not possible, aborts download. If false is given, when all given URIs do not support resume or aria2 encounters N URIs which does not support resume (N is the value specified using --max-resume-failure-tries option), aria2 downloads file from scratch. See --max-resume-failure-tries option. Default: true',
  "Settings.async-dns.desc": 'Enable asynchronous DNS. Default: true',
  "Settings.auto-file-renaming.desc": 'Rename file name if the same file already exists. This option works only in HTTP(S)/FTP download. The new file name has a dot and a number(1..9999) appended. Default: true',
  "Settings.auto-save-interval.desc": 'Save a control file(*.aria2) every SEC seconds. If 0 is given, a control file is not saved during download. aria2 saves a control file when it stops regardless of the value. The possible values are between 0 to 600. Default: 60',
  "Settings.bt-detach-seed-only.desc": 'Exclude seed only downloads when counting concurrent active downloads (See -j option). This means that if -j3 is given and this option is turned on and 3 downloads are active and one of those enters seed mode, then it is excluded from active download count (thus it becomes 2), and the next download waiting in queue gets started. But be aware that seeding item is still recognized as active download in RPC method. Default: false',
  "Settings.bt-enable-hook-after-hash-check.desc": 'Allow hook command invocation after hash check (see -V option) in BitTorrent download. By default, when hash check succeeds, the command given by --on-bt-download-complete is executed. To disable this action, give false to this option. Default: true',
  "Settings.bt-enable-lpd.desc": "Enable Local Peer Discovery. If a private flag is set in a torrent, aria2 doesn't use this feature for that download even if true is given. Default: false",
  "Settings.bt-exclude-tracker.desc": "Comma separated list of BitTorrent tracker's announce URI to remove. You can use special value * which matches all URIs, thus removes all announce URIs. When specifying * in shell command-line, don't forget to escape or quote it. See also --bt-tracker option.",
  "Settings.bt-external-ip.desc": 'Specify the external IP address to report to a BitTorrent tracker. Although this function is named external, it can accept any kind of IP addresses. IPADDRESS must be a numeric IP address.',
  "Settings.bt-force-encryption.desc": 'Requires BitTorrent message payload encryption with arc4. This is a shorthand of --bt-require-crypto --bt-min-crypto-level=arc4. This option does not change the option value of those options. If true is given, deny legacy BitTorrent handshake and only use Obfuscation handshake and always encrypt message payload. Default: false',
  "Settings.bt-hash-check-seed.desc": 'If true is given, after hash check using --check-integrity option and file is complete, continue to seed file. If you want to check file and download it only when it is damaged or incomplete, set this option to false. This option has effect only on BitTorrent download. Default: true',
  "Settings.bt-load-saved-metadata.desc": 'Before getting torrent metadata from DHT when downloading with magnet link, first try to read file saved by --bt-save-metadata option. If it is successful, then skip downloading metadata from DHT. Default: false.',
  "Settings.bt-max-open-files.desc": 'Specify maximum number of files to open in each BitTorrent download. Default: 100',
  "Settings.bt-max-peers.desc": 'Specify the maximum number of peers per torrent. 0 means unlimited. See also bt-request-peer-speed-limit option. Default: 55',
  "Settings.bt-metadata-only.desc": 'Download metadata only. The file(s) described in metadata will not be downloaded. This option has effect only when BitTorrent Magnet URI is used. See also --bt-save-metadata option. Default: false',
  "Settings.bt-min-crypto-level.desc": 'Set minimum level of encryption method. If several encryption methods are provided by a peer, aria2 chooses the lowest one which satisfies the given level. Default: plain',
  "Settings.bt-prioritize-piece.desc": 'Try to download first and last pieces of each file first. This is useful for previewing files. The argument can contain 2 keywords: head and tail. To include both keywords, they must be separated by comma. These keywords can take one parameter, SIZE. For example, if head=<SIZE> is specified, pieces in the range of first SIZE bytes of each file get higher priority. tail=<SIZE> means the range of last SIZE bytes of each file. SIZE can include K or M (1K = 1024, 1M = 1024K). If SIZE is omitted, SIZE=1M is used.',
  "Settings.bt-request-peer-speed-limit.desc": 'If the whole download speed of every torrent is lower than SPEED, aria2 temporarily increases the number of peers to try for more download speed. Configuring this option with your preferred download speed can increase your download speed in some cases. You can append K or M (1K = 1024, 1M = 1024K). Default: 50K',
  "Settings.bt-require-crypto.desc": "If true is given, aria2 doesn't accept and establish connection with legacy BitTorrent handshake(19BitTorrent protocol). Thus aria2 always uses Obfuscation handshake. Default: false",
  "Settings.bt-save-metadata.desc": 'Save metadata as .torrent file. This option has effect only when BitTorrent Magnet URI is used. The filename is hex encoded info hash with suffix .torrent. The directory to be saved is the same directory where download file is saved. If the same file already exists, metadata is not saved. See also --bt-metadata-only option. Default: false',
  "Settings.bt-seed-unverified.desc": 'Seed previously downloaded files without verifying piece hashes. Default: false',
  "Settings.bt-stop-timeout.desc": 'Stop BitTorrent download if download speed is 0 in consecutive SEC seconds. If 0 is given, this feature is disabled. Default: 0',
  "Settings.bt-tracker.desc": "Comma separated list of additional BitTorrent tracker's announce URI. These URIs are not affected by --bt-exclude-tracker option because they are added after URIs in --bt-exclude-tracker option are removed.",
  "Settings.bt-tracker-connect-timeout.desc": 'Set the connect timeout in seconds to establish connection to tracker. After the connection is established, this option makes no effect and --bt-tracker-timeout option is used instead. Default: 60',
  "Settings.bt-tracker-interval.desc": 'Set the interval in seconds between tracker requests. This completely overrides interval value and aria2 just uses this value and ignores the min interval and interval value in the response of tracker. If 0 is set, aria2 determines interval based on the response of tracker and the download progress. Default: 0',
  "Settings.bt-tracker-timeout.desc": 'Set timeout in seconds. Default: 60',
  "Settings.bt-remove-unselected-file.desc": 'Removes the unselected files when download is completed in BitTorrent. To select files, use --select-file option. If it is not used, all files are assumed to be selected. Please use this option with care because it will actually remove files from your disk. Default: false',
  "Settings.ca-certificate.desc": 'Use the client certificate in FILE. The certificate must be either in PKCS12 (.p12, .pfx) or in PEM format. PKCS12 files must contain the certificate, a key and optionally a chain of additional certificates. Only PKCS12 files with a blank import password can be opened! When using PEM, you have to specify the private key via --private-key as well. Note: WinTLS does not support PEM files at the moment. Users have to use PKCS12 files. Note: AppleTLS users should use the KeyChain Access utility to import the client certificate and get the SHA-1 fingerprint from the Information dialog corresponding to that certificate. To start aria2c use --certificate=<SHA-1>. Alternatively PKCS12 files are also supported. PEM files, however, are not supported.',
  "Settings.check-certificate.desc": 'Verify the peer using certificates specified in --ca-certificate option. Default: true',
  "Settings.check-integrity.desc": 'Check file integrity by validating piece hashes or a hash of entire file. This option has effect only in BitTorrent, Metalink downloads with checksums or HTTP(S)/FTP downloads with --checksum option. If piece hashes are provided, this option can detect damaged portions of a file and re-download them. If a hash of entire file is provided, hash check is only done when file has been already download. This is determined by file length. If hash check fails, file is re-downloaded from scratch. If both piece hashes and a hash of entire file are provided, only piece hashes are used. Default: false',
  "Settings.checksum.desc": 'Set checksum. TYPE is hash type. The supported hash type is listed in Hash Algorithms in aria2c -v. DIGEST is hex digest. For example, setting sha-1 digest looks like this: sha-1=0192ba11326fe2298c8cb4de616f4d4140213838 This option applies only to HTTP(S)/FTP downloads.',
  "Settings.conf-path.desc": 'Change the configuration file path to PATH. Default: $HOME/.aria2/aria2.conf if present, otherwise $XDG_CONFIG_HOME/aria2/aria2.conf.',
  "Settings.conditional-get.desc": 'Download file only when the local file is older than remote file. This function only works with HTTP(S) downloads only. It does not work if file size is specified in Metalink. It also ignores Content-Disposition header. If a control file exists, this option will be ignored. This function uses If-Modified-Since header to get only newer file conditionally. When getting modification time of local file, it uses user supplied filename(see --out option) or filename part in URI if --out is not specified. To overwrite existing file, --allow-overwrite is required. Default: false',
  "Settings.connect-timeout.desc": 'Set the connect timeout in seconds to establish connection to HTTP/FTP/proxy server. After the connection is established, this option makes no effect and --timeout option is used instead. Default: 60',
  "Settings.console-log-level.desc": 'Set log level to output to console. LEVEL is either debug, info, notice, warn or error. Default: notice',
  "Settings.content-disposition-default-utf8.desc": 'Handle quoted string in Content-Disposition header as UTF-8 instead of ISO-8859-1, for example, the filename parameter, but not the extended version filename*. Default: false.',
  "Settings.continue.desc": 'Continue downloading a partially downloaded file. Use this option to resume a download started by a web browser or another program which downloads files sequentially from the beginning. Currently this option is only applicable to HTTP(S)/FTP downloads.',
  "Settings.daemon.desc": 'Run as daemon. The current working directory will be changed to / and standard input, standard output and standard error will be redirected to /dev/null. Default: false',
  "Settings.deferred-input.desc": 'If true is given, aria2 does not read all URIs and options from file specified by --input-file option at startup, but it reads one by one when it needs later. This may reduce memory usage if input file contains a lot of URIs to download. If false is given, aria2 reads all URIs and options at startup. Default: false',
  "Settings.download-result.desc": 'This option changes the way Download Results is formatted. If OPT is default, print GID, status, average download speed and path/URI. If multiple files are involved, path/URI of first requested file is printed and remaining ones are omitted. If OPT is full, print GID, status, average download speed, percentage of progress and path/URI. The percentage of progress and path/URI are printed for each requested file in each row. Default: default',
  "Settings.dht-file-path.desc": 'Change the IPv4 DHT routing table file to PATH. Default: $HOME/.aria2/dht.dat if present, otherwise $XDG_CACHE_HOME/aria2/dht.dat.',
  "Settings.dht-file-path6.desc": 'Change the IPv6 DHT routing table file to PATH. Default: $HOME/.aria2/dht6.dat if present, otherwise $XDG_CACHE_HOME/aria2/dht6.dat.',
  "Settings.dht-listen-port.desc": 'Set UDP listening port used by DHT(IPv4, IPv6) and UDP tracker. Multiple ports can be specified by using ,, for example: 6881,6885. You can also use - to specify a range: 6881-6999. , and - can be used together. Default: 6881-6999. Note: Make sure that the specified ports are open for incoming UDP traffic.',
  "Settings.dht-message-timeout.desc": 'Set timeout in seconds. Default: 10',
  "Settings.disk-cache.desc": "Enable disk cache. If SIZE is 0, the disk cache is disabled. This feature caches the downloaded data in memory, which grows to at most SIZE bytes. The cache storage is created for aria2 instance and shared by all downloads. The one advantage of the disk cache is reduce the disk I/O because the data are written in larger unit and it is reordered by the offset of the file. If hash checking is involved and the data are cached in memory, we don't need to read them from the disk. SIZE can include K or M (1K = 1024, 1M = 1024K). Default: 16M.",
  "Settings.dir.desc": 'The directory to store the downloaded file.',
  "Settings.disable-ipv6.desc": 'Disable IPv6. This is useful if you have to use broken DNS and want to avoid terribly slow AAAA record lookup. Default: false',
  "Settings.dry-run.desc": "If true is given, aria2 just checks whether the remote file is available and doesn't download data. This option has effect on HTTP/FTP download. BitTorrent downloads are canceled if true is specified. Default: false",
  "Settings.dscp.desc": "Set DSCP value in outgoing IP packets of BitTorrent traffic for QoS. This parameter sets only DSCP bits in TOS field of IP packets, not the whole field. If you take values from /usr/include/netinet/ip.h divide them by 4 (otherwise values would be incorrect, e.g. your CS1 class would turn into CS4). If you take commonly used values from RFC, network vendors' documentation, Wikipedia or any other source, use them as they are.",
  "Settings.enable-async-dns6.desc": 'Enable IPv6 name resolution in asynchronous DNS resolver. This option will be ignored when --async-dns=false. Default: false',
  "Settings.enable-color.desc": 'Enable color output for a terminal. Default: true',
  "Settings.enable-dht.desc": 'Enable IPv4 DHT functionality. It also enables UDP tracker support. If a private flag is set in a torrent, aria2 doesn’t use DHT for that download even if true is given. Default: true',
  "Settings.enable-dht6.desc": 'Enable IPv6 DHT functionality. If a private flag is set in a torrent, aria2 doesn’t use DHT for that download even if true is given. Use --dht-listen-port option to specify port number to listen on. See also --dht-listen-addr6 option.',
  "Settings.enable-http-keep-alive.desc": 'Enable HTTP/1.1 persistent connection. Default: true',
  "Settings.enable-http-pipelining.desc": 'Enable HTTP/1.1 pipelining. Default: false',
  "Settings.enable-peer-exchange.desc": 'Enable Peer Exchange extension. If a private flag is set in a torrent, this feature is disabled for that download even if true is given. Default: true',
  "Settings.enable-mmap.desc": 'Map files into memory. This option may not work if the file space is not pre-allocated. See --file-allocation. Default: false',
  "Settings.enable-rpc.desc": 'Enable JSON-RPC/XML-RPC server. It is strongly recommended to set secret authorization token using --rpc-secret option. See also --rpc-listen-port option. Default: false',
  "Settings.event-poll.desc": 'Specify the method for polling events. The possible values are epoll, kqueue, port, poll and select. For each epoll, kqueue, port and poll, it is available if system supports it. epoll is available on recent Linux. kqueue is available on various *BSD systems including Mac OS X. port is available on Open Solaris. The default value may vary depending on the system you use.',
  "Settings.help.desc": 'The help messages are classified with tags. A tag starts with #. For example, type --help=#http to get the usage for the options tagged with #http. If non-tag word is given, print the usage for the options whose name includes that word. Available Values: #basic, #advanced, #http, #https, #ftp, #metalink, #bittorrent, #cookie, #hook, #file, #rpc, #checksum, #experimental, #deprecated, #help, #all Default: #basic.',
  "Settings.file-allocation.desc": "Specify file allocation method. none doesn't pre-allocate file space. prealloc pre-allocates file space before download begins. This may take some time depending on the size of the file. If you are using newer file systems such as ext4 (with extents support), btrfs, xfs or NTFS(MinGW build only), falloc is your best choice. It allocates large(few GiB) files almost instantly. Don't use falloc with legacy file systems such as ext3 and FAT32 because it takes almost same time as prealloc and it blocks aria2 entirely until allocation finishes. falloc may not be available if your system doesn't have posix_fallocate(3) function. Possible Values: none, prealloc, falloc Default: prealloc",
  "Settings.follow-metalink.desc": 'If true or mem is specified, when a file whose suffix is .meta4 or .metalink or content type of application/metalink4+xml or application/metalink+xml is downloaded, aria2 parses it as a metalink file and downloads files mentioned in it. If mem is specified, a metalink file is not written to the disk, but is just kept in memory. If false is specified, the action mentioned above is not taken. Default: true',
  "Settings.follow-torrent.desc": 'If true or mem is specified, when a file whose suffix is .torrent or content type is application/x-bittorrent is downloaded, aria2 parses it as a torrent file and downloads files mentioned in it. If mem is specified, a torrent file is not written to the disk, but is just kept in memory. If false is specified, the action mentioned above is not taken. Default: true',
  "Settings.force-save.desc": 'Save download with --save-session option even if the download is completed or removed. This option also saves control file in that situations. This may be useful to save BitTorrent seeding which is recognized as completed state. Default: false',
  "Settings.ftp-passwd.desc": 'Set FTP password. This affects all URIs. If user name is embedded but password is missing in URI, aria2 tries to resolve password using .netrc. If password is found in .netrc, then use it as password. If not, use the password specified in this option. Default: ARIA2USER@',
  "Settings.ftp-pasv.desc": 'Use the passive mode in FTP. If false is given, the active mode will be used. Default: true',
  "Settings.ftp-proxy.desc": '',
  "Settings.ftp-proxy-passwd.desc": 'Set password for --ftp-proxy option.',
  "Settings.ftp-proxy-user.desc": 'Set user for --ftp-proxy option.',
  "Settings.ftp-reuse-connection.desc": 'Reuse connection in FTP. Default: true.',
  "Settings.ftp-type.desc": 'Set FTP transfer type. TYPE is either binary or ascii. Default: binary',
  "Settings.ftp-user.desc": 'Set FTP user. This affects all URIs. Default: anonymous',
  "Settings.hash-check-only.desc": 'If true is given, after hash check using --check-integrity option, abort download whether or not download is complete. Default: false',
  "Settings.header.desc": 'Append HEADER to HTTP request header.',
  "Settings.http-accept-gzip.desc": 'Send Accept: deflate, gzip request header and inflate response if remote server responds with Content-Encoding: gzip or Content-Encoding: deflate. Default: false',
  "Settings.http-auth-challenge.desc": 'Send HTTP authorization header only when it is requested by the server. If false is set, then authorization header is always sent to the server. There is an exception: if username and password are embedded in URI, authorization header is always sent to the server regardless of this option. Default: false',
  "Settings.http-no-cache.desc": 'Send Cache-Control: no-cache and Pragma: no-cache header to avoid cached content. If false is given, these headers are not sent and you can add Cache-Control header with a directive you like using --header option. Default: true',
  "Settings.http-user.desc": 'Set HTTP username.',
  "Settings.http-passwd.desc": 'Set HTTP password.',
  "Settings.http-proxy.desc": '',
  "Settings.http-proxy-passwd.desc": 'Set password for --http-proxy option.',
  "Settings.http-proxy-user.desc": 'Set user for --http-proxy option.',
  "Settings.human-readable.desc": 'Print sizes and speed in human readable format (e.g., 1.2Ki, 3.4Mi) in the console readout. Default: true',
  "Settings.index-out.desc": 'Set file path for file with index=INDEX. You can find the file index using the --show-files option. PATH is a relative path to the path specified in --dir option. You can use this option multiple times. Using this option, you can specify the output filenames of BitTorrent downloads.',
  "Settings.keep-unfinished-download-result.desc": 'Keep unfinished download results even if doing so exceeds --max-download-result. This is useful if all unfinished downloads must be saved in session file (see --save-session option). Please keep in mind that there is no upper bound to the number of unfinished download result to keep. If that is undesirable, turn this option off. Default: true.',
  "Settings.listen-port.desc": 'Set TCP port number for BitTorrent downloads. Multiple ports can be specified by using ,, for example: 6881,6885. You can also use - to specify a range: 6881-6999. , and - can be used together: 6881-6889,6999. Default: 6881-6999. Note: Make sure that the specified ports are open for incoming TCP traffic.',
  "Settings.log": 'The file name of the log file. If - is specified, log is written to stdout. If empty string("") is specified, or this option is omitted, no log is written to disk at all.',
  "Settings.log-level.desc": 'Set log level to output. LEVEL is either debug, info, notice, warn or error. Default: debug.',
  "Settings.lowest-speed-limit.desc": 'Close connection if download speed is lower than or equal to this value(bytes per sec). 0 means aria2 does not have a lowest speed limit. You can append K or M (1K = 1024, 1M = 1024K). This option does not affect BitTorrent downloads. Default: 0',
  "Settings.max-concurrent-downloads.desc": 'Set maximum number of parallel downloads for every static (HTTP/FTP) URI, torrent and metalink. See also --split option. Default: 5',
  "Settings.max-connection-per-server.desc": 'The maximum number of connections to one server for each download. Default: 1',
  "Settings.max-download-limit.desc": 'Set max download speed per each download in bytes/sec. 0 means unrestricted. You can append K or M (1K = 1024, 1M = 1024K). To limit the overall download speed, use --max-overall-download-limit option. Default: 0',
  "Settings.max-download-result.desc": 'Set maximum number of download result kept in memory. The download results are completed/error/removed downloads. The download results are stored in FIFO queue and it can store at most NUM download results. When queue is full and new download result is created, oldest download result is removed from the front of the queue and new one is pushed to the back. Setting big number in this option may result high memory consumption after thousands of downloads. Specifying 0 means no download result is kept. Default: 1000',
  "Settings.max-file-not-found": '',
  "Settings.max-mmap-limit.desc": 'Set the maximum file size to enable mmap (see --enable-mmap option). The file size is determined by the sum of all files contained in one download. For example, if a download contains 5 files, then file size is the total size of those files. If file size is strictly greater than the size specified in this option, mmap will be disabled. Default: 9223372036854775807.',
  "Settings.max-overall-download-limit.desc": 'Set max overall download speed in bytes/sec. 0 means unrestricted. You can append K or M (1K = 1024, 1M = 1024K). To limit the download speed per download, use --max-download-limit option. Default: 0.',
  "Settings.max-overall-upload-limit.desc": 'Set max overall upload speed in bytes/sec. 0 means unrestricted. You can append K or M (1K = 1024, 1M = 1024K). To limit the upload speed per torrent, use --max-upload-limit option. Default: 0.',
  "Settings.max-resume-failure-tries.desc": 'When used with --always-resume=false, aria2 downloads file from scratch when aria2 detects N number of URIs that does not support resume. If N is 0, aria2 downloads file from scratch when all given URIs do not support resume. See --always-resume option. Default: 0',
  "Settings.max-tries.desc": 'Set number of tries. 0 means unlimited. See also --retry-wait. Default: 5',
  "Settings.max-upload-limit.desc": 'Set max upload speed per each torrent in bytes/sec. 0 means unrestricted. You can append K or M (1K = 1024, 1M = 1024K). To limit the overall upload speed, use --max-overall-upload-limit option. Default: 0',
  "Settings.metalink-base-uri.desc": 'Specify base URI to resolve relative URI in metalink:url and metalink:metaurl element in a metalink file stored in local disk. If URI points to a directory, URI must end with /.',
  "Settings.metalink-enable-unique-protocol.desc": 'If true is given and several protocols are available for a mirror in a metalink file, aria2 uses one of them. Use --metalink-preferred-protocol option to specify the preference of protocol. Default: true',
  "Settings.metalink-language.desc": 'The language of the file to download.',
  "Settings.metalink-location.desc": 'The location of the preferred server. A comma-delimited list of locations is acceptable, for example, jp,us.',
  "Settings.metalink-preferred-protocol.desc": 'Specify preferred protocol. The possible values are http, https, ftp and none. Specify none to disable this feature. Default: none.',
  "Settings.metalink-os.desc": 'The operating system of the file to download.',
  "Settings.metalink-version.desc": 'The version of the file to download.',
  "Settings.min-split-size.desc": "aria2 does not split less than 2*SIZE byte range. For example, let's consider downloading 20MiB file. If SIZE is 10M, aria2 can split file into 2 range [0-10MiB) and [10MiB-20MiB) and download it using 2 sources(if --split >= 2, of course). If SIZE is 15M, since 2*15M > 20MiB, aria2 does not split file and download it using 1 source. You can append K or M (1K = 1024, 1M = 1024K). Possible Values: 1M -1024M Default: 20M",
  "Settings.min-tls-version.desc": 'Указать для использования минимальную версию SSL/TLS. Возможные значения: SSLv3, TLSv1, TLSv1.1, TLSv1.2 По умолчанию: TLSv1.2.',
  "Settings.netrc-path.desc": 'Specify the path to the netrc file. Default: $(HOME)/.netrc. Note: Permission of the .netrc file must be 600. Otherwise, the file will be ignored.',
  "Settings.no-conf.desc": 'Disable loading aria2.conf file.',
  "Settings.no-file-allocation-limit.desc": 'No file allocation is made for files whose size is smaller than SIZE. You can append K or M (1K = 1024, 1M = 1024K). Default: 5M',
  "Settings.no-netrc.desc": 'Disables netrc support. netrc support is enabled by default.Note netrc file is only read at the startup if --no-netrc is false. So if --no-netrc is true at the startup, no netrc is available throughout the session. You cannot get netrc enabled even if you change this setting.',
  "Settings.no-proxy.desc": 'Specify comma separated hostnames, domains and network address with or without CIDR block where proxy should not be used.',
  "Settings.on-bt-download-complete.desc": 'For BitTorrent, a command specified in --on-download-complete is called after download completed and seeding is over. On the other hand, this option set the command to be executed after download completed but before seeding. See Event Hook for more details about COMMAND. Possible Values: /path/to/command.',
  "Settings.on-download-complete.desc": 'Set the command to be executed after download completed. See Event Hook(https://aria2.github.io/manual/en/html/aria2c.html#event-hook) for more details about COMMAND. See also --on-download-stop option. Possible Values: /path/to/command.',
  "Settings.optimize-concurrent-downloads.desc": 'Optimizes the number of concurrent downloads according to the bandwidth available. aria2 uses the download speed observed in the previous downloads to adapt the number of downloads launched in parallel according to the rule N = A + B Log10(speed in Mbps). The coefficients A and B can be customized in the option arguments with A and B separated by a colon. The default values (A=5, B=25) lead to using typically 5 parallel downloads on 1Mbps networks and above 50 on 100Mbps networks. The number of parallel downloads remains constrained under the maximum defined by the --max-concurrent-downloads parameter. Default: false.',
  "Settings.out.desc": 'The file name of the downloaded file. When --force-sequential option is used, this option is ignored.',
  "Settings.parameterized-uri.desc": 'Enable parameterized URI support. You can specify set of parts: http://{sv1,sv2,sv3}/foo.iso. Also you can specify numeric sequences with step counter: http://host/image[000-100:2].img. A step counter can be omitted. If all URIs do not point to the same file, such as the second example above, -Z option is required. Default: false',
  "Settings.pause.desc": 'Pause download after added. This option is effective only when --enable-rpc=true is given. Default: false',
  "Settings.pause-metadata.desc": 'Pause downloads created as a result of metadata download. There are 3 types of metadata downloads in aria2: (1) downloading .torrent file. (2) downloading torrent metadata using magnet link. (3) downloading metalink file. These metadata downloads will generate downloads using their metadata. This option pauses these subsequent downloads. This option is effective only when --enable-rpc=true is given. Default: false',
  "Settings.peer-agent.desc": "Specify the string used during the bitorrent extended handshake for the peer's client version. Default: aria2/$MAJOR.$MINOR.$PATCH, $MAJOR, $MINOR and $PATCH are replaced by major, minor and patch version number respectively. For instance, aria2 version 1.18.8 has peer agent aria2/1.18.8.",
  "Settings.peer-id-prefix.desc": 'Specify the prefix of peer ID. The peer ID in BitTorrent is 20 byte length. If more than 20 bytes are specified, only first 20 bytes are used. If less than 20 bytes are specified, random byte data are added to make its length 20 bytes.Default: A2-$MAJOR-$MINOR-$PATCH-, $MAJOR, $MINOR and $PATCH are replaced by major, minor and patch version number respectively. For instance, aria2 version 1.18.8 has prefix ID A2-1-18-8-.',
  "Settings.piece-length.desc": 'Set a piece length for HTTP/FTP downloads. This is the boundary when aria2 splits a file. All splits occur at multiple of this length. This option will be ignored in BitTorrent downloads. It will be also ignored if Metalink file contains piece hashes. Default: 1M',
  "Settings.proxy-method.desc": 'Set the method to use in proxy request. METHOD is either get or tunnel. HTTPS downloads always use tunnel regardless of this option. Default: get',
  "Settings.quiet.desc": 'Make aria2 quiet (no console output). Default: false',
  "Settings.realtime-chunk-checksum.desc": 'Validate chunk of data by calculating checksum while downloading a file if chunk checksums are provided. Default: true',
  "Settings.referer.desc": 'Set Referer. This affects all URIs.',
  "Settings.remote-time.desc": 'Retrieve timestamp of the remote file from the remote HTTP/FTP server and if it is available, apply it to the local file. Default: false',
  "Settings.remove-control-file.desc": 'Remove control file before download. Using with --allow-overwrite=true, download always starts from scratch. This will be useful for users behind proxy server which disables resume.',
  "Settings.retry-wait.desc": 'Set the seconds to wait between retries. With SEC > 0, aria2 will retry download when the HTTP server returns 503 response. Default: 0.',
  "Settings.reuse-uri.desc": 'Reuse already used URIs if no unused URIs are left. Default: true',
  "Settings.rlimit-nofile.desc": 'Set the soft limit of open file descriptors. This open will only have effect when:<br/>The system supports it (posix)<br/>The limit does not exceed the hard limit.<br/>The specified limit is larger than the current soft limit.<br/>his is equivalent to setting nofile via ulimit, except that it will never decrease the limit.<br/>This option is only available on systems supporting the rlimit API.',
  "Settings.rpc-certificate.desc": 'Use the certificate in FILE for RPC server. The certificate must be either in PKCS12 (.p12, .pfx) or in PEM format. PKCS12 files must contain the certificate, a key and optionally a chain of additional certificates. Only PKCS12 files with a blank import password can be opened! When using PEM, you have to specify the private key via --rpc-private-key as well. Use --rpc-secure option to enable encryption. Note: WinTLS does not support PEM files at the moment. Users have to use PKCS12 files. Note: AppleTLS users should use the KeyChain Access utility to first generate a self-signed SSL-Server certificate, e.g. using the wizard, and get the SHA-1 fingerprint from the Information dialog corresponding to that new certificate. To start aria2c with --rpc-secure use --rpc-certificate=<SHA-1>. Alternatively PKCS12 files are also supported. PEM files, however, are not supported.',
  "Settings.rpc-listen-port.desc": 'Specify a port number for JSON-RPC/XML-RPC server to listen to. Possible Values: 1024 -65535 Default: 6800.',
  "Settings.rpc-max-request-size.desc": 'Set max size of JSON-RPC/XML-RPC request. If aria2 detects the request is more than SIZE bytes, it drops connection. Default: 2M.',
  "Settings.rpc-private-key.desc": 'Use the private key in FILE for RPC server. The private key must be decrypted and in PEM format. Use --rpc-secure option to enable encryption. See also --rpc-certificate option.',
  "Settings.rpc-save-upload-metadata.desc": "Save the uploaded torrent or metalink meta data in the directory specified by --dir option. The file name consists of SHA-1 hash hex string of meta data plus extension. For torrent, the extension is '.torrent'. For metalink, it is '.meta4'. If false is given to this option, the downloads added by aria2.addTorrent() or aria2.addMetalink() will not be saved by --save-session option. Default: true.",
  "Settings.save-cookies.desc": 'Save Cookies to FILE in Mozilla/Firefox(1.x/2.x)/ Netscape format. If FILE already exists, it is overwritten. Session Cookies are also saved and their expiry values are treated as 0. Possible Values: /path/to/file.',
  "Settings.save-not-found.desc": 'Save download with --save-session option even if the file was not found on the server. This option also saves control file in that situations. Default: true.',
  "Settings.save-session.desc": 'Save error/unfinished downloads to FILE on exit. You can pass this output file to aria2c with --input-file option on restart.',
  "Settings.save-session-interval.desc": 'Save error/unfinished downloads to a file specified by --save-session option every SEC seconds. If 0 is given, file will be saved only when aria2 exits. Default: 0.',
  "Settings.seed-ratio.desc": 'Specify share ratio. Seed completed torrents until share ratio reaches RATIO. You are strongly encouraged to specify equals or more than 1.0 here. Specify 0.0 if you intend to do seeding regardless of share ratio. If --seed-time option is specified along with this option, seeding ends when at least one of the conditions is satisfied. Default: 1.0',
  "Settings.seed-time.desc": 'Specify seeding time in minutes. Also see the --seed-ratio option. Note Specifying --seed-time=0 disables seeding after download completed.',
  "Settings.select-file.desc": 'Set file to download by specifying its index. You can find the file index using the --show-files option. Multiple indexes can be specified by using ,, for example: 3,6. You can also use - to specify a range: 1-5. , and - can be used together: 1-5,8,9. When used with the -M option, index may vary depending on the query .',
  "Settings.server-stat-of.desc": 'Specify the filename to which performance profile of the servers is saved. You can load saved data using --server-stat-if option. See Server Performance Profile subsection below for file format.',
  "Settings.server-stat-timeout.desc": 'Specifies timeout in seconds to invalidate performance profile of the servers since the last contact to them. Default: 86400 (24hours)',
  "Settings.socket-recv-buffer-size.desc": 'Set the maximum socket receive buffer in bytes. Specifying 0 will disable this option. This value will be set to socket file descriptor using SO_RCVBUF socket option with setsockopt() call. Default: 0.',
  "Settings.split.desc": 'Download a file using N connections. If more than N URIs are given, first N URIs are used and remaining URIs are used for backup. If less than N URIs are given, those URIs are used more than once so that N connections total are made simultaneously. The number of connections to the same host is restricted by --max-connection-per-server option. See also --min-split-size option. Default: 5',
  "Settings.stderr.desc": 'Redirect all console output that would be otherwise printed in stdout to stderr. Default: false.',
  "Settings.stop.desc": 'Stop application after SEC seconds has passed. If 0 is given, this feature is disabled. Default: 0.',
  "Settings.summary-interval.desc": 'Set interval in seconds to output download progress summary. Setting 0 suppresses the output. Default: 60',
  "Settings.timeout.desc": 'Set timeout in seconds. Default: 60',
  "Settings.rpc-allow-origin-all.desc": 'Add Access-Control-Allow-Origin header field with value * to the RPC response. Default: false',
  "Settings.rpc-listen-all.desc": 'Listen incoming JSON-RPC/XML-RPC requests on all network interfaces. If false is given, listen only on local loopback interface. Default: false',
  "Settings.rpc-secure.desc": 'RPC transport will be encrypted by SSL/TLS. The RPC clients must use https scheme to access the server. For WebSocket client, use wss scheme. Use --rpc-certificate and --rpc-private-key options to specify the server certificate and private key.',
  "Settings.stream-piece-selector.desc": 'Specify piece selection algorithm used in HTTP/FTP download. Piece means fixed length segment which is downloaded in parallel in segmented download. If default is given, aria2 selects piece so that it reduces the number of establishing connection. This is reasonable default behaviour because establishing connection is an expensive operation. If inorder is given, aria2 selects piece which has minimum index. Index=0 means first of the file. This will be useful to view movie while downloading it. --enable-http-pipelining option may be useful to reduce reconnection overhead. Please note that aria2 honors --min-split-size option, so it will be necessary to specify a reasonable value to --min-split-size option. If geom is given, at the beginning aria2 selects piece which has minimum index like inorder, but it exponentially increasingly keeps space from previously selected piece. This will reduce the number of establishing connection and at the same time it will download the beginning part of the file first. This will be useful to view movie while downloading it. Default: default',
  "Settings.show-console-readout.desc": 'Show console readout. Default: true',
  "Settings.show-files.desc": 'Print file listing of “.torrent”, “.meta4” and “.metalink” file and exit. In case of “.torrent” file, additional information (infohash, piece length, etc) is also printed.',
  "Settings.truncate-console-readout.desc": 'Truncate console readout to fit in a single line. Default: true',
  "Settings.uri-selector.desc": "Specify URI selection algorithm. The possible values are inorder, feedback and adaptive. If inorder is given, URI is tried in the order appeared in the URI list. If feedback is given, aria2 uses download speed observed in the previous downloads and choose fastest server in the URI list. This also effectively skips dead mirrors. The observed download speed is a part of performance profile of servers mentioned in --server-stat-of and --server-stat-if options. If adaptive is given, selects one of the best mirrors for the first and reserved connections. For supplementary ones, it returns mirrors which has not been tested yet, and if each of them has already been tested, returns mirrors which has to be tested again. Otherwise, it doesn't select anymore mirrors. Like feedback, it uses a performance profile of servers. Default: feedback",
  "Settings.use-head.desc": 'Use HEAD method for the first request to the HTTP server. Default: false',
  "Settings.user-agent.desc": 'Set user agent for HTTP(S) downloads. Default: aria2/$VERSION, $VERSION is replaced by package version.'
};
