# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master,newgen ]

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 14.x
    - uses: actions/cache@v2.1.0
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: buildandpush
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if git log --format=%B -n 1 $(git rev-parse HEAD)|grep -v "Docs Update"; then
          node node_modules/webpack-cli/bin/cli.js
          git add -A
          git commit -m "Docs Update $(git rev-parse --short HEAD)+$(git show -s --format=%ci $(git rev-parse HEAD)|tr ' ' '-')"
          git remote set-url origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_ACTOR}/webui-aria2.git
          git push
        else
          echo 'Do nothing'
        fi

